### ISSUE TITLE
Some questions about label refinery and its difference with knowledge distillation

### ISSUE THREAD

**Issue by bowenc0221** [hessamb/label-refinery#1]
Hi,

Good job! This is a very interesting work!
After reading the paper, I have some questions about details.
1. For each label refinery network, do you train it to converge (i.e. 200 epochs mentioned in the paper)? For example, you first train AlexNet^1 for 200 epochs and then AlexNet^2 for another 200 epochs?
2. If 1. is the case, then label refinement is the same as knowledge distillation to me (setting the temperature term to 1), if Adversarial Jittering is not used. In my understanding, knowledge distillation is (or could be) also done at crop level. Is there any difference between knowledge distillation and label refinery?

Thanks in advance.

**Comment by hessamb** [comment]
Thanks!

1. Yep we train each network to convergence.
2. Yeah I guess our method and loss is very similar to knowledge distillation. Knowledge distillation works, we show that it does in some of our results. We show some other cool stuff too. We show that it's not just *distilling the knowledge* from a more accurate network that helps, because even the same network generating labels for the exact same model gives significant improvements. We think this works because of the *per-crop label problem*. We even saw that a more accurate model (VGG16 at 70 top1) can significantly benefit from training with labels generated by a less accurate model (MobileNet at 68.5 top1), because they are still better than ground-truth labels. We then show that often doing this for multiple iterations helps further, because labels are becoming better and better.
